Tested Project Using An AWS EC2 Ubuntu Instance: - Changed ansible inventory file hostname to 'homeAssistantServer' from 'raspberryPi' - Updated ansible playbook/role: Shifted apt update to before python is installed - Updated ansible playbook/role: Added installation of unzip package - Updated ansible playbook/role: Added creation of ~/.bash_profile if it does not exist - Updated ansible playbook/role: Added necessary repositories for Ubuntu distributions - Updated ansible playbook/role: Added the installation of ansible dependencies like pip and six - Updated ansible playbook/role: Skip amending of rc.local if it does not exist - Updated ansible playbook/role: Updated docker GPG key & repository to work with Ubuntu distributions - Updated ansible playbook/role: Added gnupg installation as a docker dependency - Updated ansible playbook/role: Shifted xiaomi miot integration addition to the browser UI, commented out relevant portions - Updated ansible playbook/role: Added creation of mosquitto.conf file if it does not exist - Improved formatting for README.md file

diff --git a/Ansible/roles/setupHAAddOns/tasks/main.yml b/Ansible/roles/setupHAAddOns/tasks/main.yml
--- a/Ansible/roles/setupHAAddOns/tasks/main.yml
+++ b/Ansible/roles/setupHAAddOns/tasks/main.yml
@@ -12,48 +12,48 @@
       register: hacs_result
       changed_when: "'successfully installed' in hacs_result.stdout or 'already up to date' not in hacs_result.stdout"
 
-    #Xiaomi MIOT Integration
-    - name: Rename old Xiaomi Miot ZIP if it exists
-      ansible.builtin.command:
-        cmd: "mv /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip"
-      args:
-        removes: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip"
-      ignore_errors: true
+    # #Xiaomi MIOT Integration
+    # - name: Rename old Xiaomi Miot ZIP if it exists
+    #   ansible.builtin.command:
+    #     cmd: "mv /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip"
+    #   args:
+    #     removes: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip"
+    #   ignore_errors: true
 
-    - name: Download Xiaomi Miot integration ZIP
-      ansible.builtin.get_url:
-        url: "https://ghrp.hacs.vip/al-one/hass-xiaomi-miot/releases/latest/download/xiaomi_miot.zip"
-        dest: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip"
-        mode: '0644'
-        force: true  # Always download the latest version even if the file exists
-      register: download_result
+    # - name: Download Xiaomi Miot integration ZIP
+    #   ansible.builtin.get_url:
+    #     url: "https://ghrp.hacs.vip/al-one/hass-xiaomi-miot/releases/latest/download/xiaomi_miot.zip"
+    #     dest: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip"
+    #     mode: '0644'
+    #     force: true  # Always download the latest version even if the file exists
+    #   register: download_result
 
-    - name: Compare new and old Xiaomi Miot ZIP files 
-      ansible.builtin.shell: |
-        if [ -f /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip ]; then 
-          diff /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip
-        else
-          exit 1
-        fi
-      register: zip_diff_result
-      changed_when: zip_diff_result.rc != 0
-      ignore_errors: true
+    # - name: Compare new and old Xiaomi Miot ZIP files 
+    #   ansible.builtin.shell: |
+    #     if [ -f /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip ]; then 
+    #       diff /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip /home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip
+    #     else
+    #       exit 1
+    #     fi
+    #   register: zip_diff_result
+    #   changed_when: zip_diff_result.rc != 0
+    #   ignore_errors: true
 
-    - name: Remove old Xiaomi Miot integration if ZIP changed
-      ansible.builtin.file:
-        path: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot"
-        state: absent
-      when: zip_diff_result.changed
+    # - name: Remove old Xiaomi Miot integration if ZIP changed
+    #   ansible.builtin.file:
+    #     path: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot"
+    #     state: absent
+    #   when: zip_diff_result.changed
 
-    - name: Extract new Xiaomi Miot integration if ZIP changed
-      ansible.builtin.unarchive:
-        src: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip"
-        dest: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot"
-        remote_src: true
-        extra_opts: [--strip-components=1]
-      when: zip_diff_result.changed
+    # - name: Extract new Xiaomi Miot integration if ZIP changed
+    #   ansible.builtin.unarchive:
+    #     src: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot.zip"
+    #     dest: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot"
+    #     remote_src: true
+    #     extra_opts: ["-o"]
+    #   when: zip_diff_result.changed
 
-    - name: Cleanup old Xiaomi Miot ZIP file
-      ansible.builtin.file:
-        path: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip"
-        state: absent
+    # - name: Cleanup old Xiaomi Miot ZIP file
+    #   ansible.builtin.file:
+    #     path: "/home/{{ ansible_user }}/homeAssistant/custom_components/xiaomi_miot_old.zip"
+    #     state: absent
